### ISSUE TITLE
Access denied

### ISSUE THREAD

**Issue by fridsamt** [hyperic/hq#10]
When I was trying to compile the source code of 5.8.4.3, I encountered the error that some dependencies could not be resolved:
 
Failed to execute goal on project appha-internal-plugin: Could not resolve dependencies for project org.hyperic.hq.plugin:appha-internal-plugin:jar:5.8.4.3: Could not transfer artifact org.hyperic.hq:hq-util:jar:tests:5.8.4.3 from/to cm-release (http://maven.cm.hyperic.org/release): Access denied to: http://maven.cm.hyperic.org/release/org/hyperic/hq/hq-util/5.8.4.3/hq-util-5.8.4.3-tests.jar , ReasonPhrase:Forbidden. -> [Help 1]

And when I trying to install the schema, it seems that the hq-migration-5.8.4.3.pom could not be downloaded either. 
And I had the same error when trying 5.8.4
How could I get these files?

Thank you

**Comment by yborenstein** [comment]
How did you run mvn?
use:
mvn clean install -T 1.5C -DCI-build -Dall-installers -DskipTests
or
mvn clean install -T 1.5C  -Dall-installers -DskipTests

**Comment by fridsamt** [comment]
Thanks, it works.
BTW, I want to write an SNMP plugin, is the way on https://support.hyperic.com/display/DOCS46/Write+an+SNMP+Plugin still work for version 5.8.4? Because I found it's for version 4.6.

**Comment by yborenstein** [comment]
Yes, It should work
