### ISSUE TITLE
Metrics took too long to run (*ms), cancelled (result=true)

### ISSUE THREAD

**Issue by AnanAdel** [hyperic/hq#16]
Hyperic agent giving the subjected error in logs, I have reinstall hq-agent from scratch multiple times and on different servers but that did not help me so I believe this is a bug.

I have opened a discussion on Hyperic forums below link:
https://communities.vmware.com/thread/536216

And logs on the link:
https://communities.vmware.com/servlet/JiveServlet/download/2597683-156589/logs.zip

**Comment by yborenstein** [comment]
The issue is related the some registry issue:
Edit the registry to make sure the Windows Performance Counters were not disabled.

**Comment by AnanAdel** [comment]
@yborenstein Thanks indeed for your support, issue solved.
