### ISSUE TITLE
 Failed to execute goal on project hq-server: Could not resolve dependencies for

### ISSUE THREAD

**Issue by hackereye** [hyperic/hq#2]
Failed to execute goal on project hq-server: Could not resolve dependencies for project org.hyperic.hq:hq-server:jar:5.8.2.1: Could not transfer artifact org.hyperic.hq:hq-util:jar:tests:5.8.2.1 from/to cm-release (http://maven.cm.hyperic.org/release): Access denied to: http://maven.cm.hyperic.org/release/org/hyperic/hq/hq-util/5.8.2.1/hq-util-5.8.2.1-tests.jar , ReasonPhrase:Forbidden. ->

**Comment by yborenstein** [comment]
run
mvn clean install -T 1.5C  -Dall-installers -DskipTests
or
mvn clean install -T 1.5C -DCI-build -Dall-installers -DskipTests
