### ISSUE TITLE
when install on linux 64, it reports Failed to create keystore:hq, timeout after 300000ms

### ISSUE THREAD

**Issue by martinking1997** [hyperic/hq#9]
The details is:
when run setup.sh from  hyperic-hq-installer-x86-64-linux-5.8.4.2.tar.gz.
After input: 
What should the email address be for the initial admin user? [default 'hqadmin@168.1.126']:
It aborted with:
An ERROR occurred, the installation cannot continue.
FATAL EXCEPTION at /home/laowang/temp/hyperic-hq-installer-5.8.4.2/installer/data/setup.xml:157: : The following error occurred while executing this line:
/home/laowang/temp/hyperic-hq-installer-5.8.4.2/installer/data/setup-interactive.xml:15: java.security.KeyStoreException: Failed to create keystore:hq, timeout after 300000ms

I think it is related to the new jdk version.

**Comment by tgoldman** [comment]
Hyperic server 5.8.4.2 is not an official release.
It is a bug due to the new jre version.
Please use Hyperic 5.8.4 version or replace the jre file under installer directory with the 5.8.4 corresponding file.

**Comment by yborenstein** [comment]
you can use 5.8.x branch
